{% set version = "1.1.5" %}
{% set xorg_category = "lib" %}
{% set xorg_name = "libXinerama" %}
{% set name = "xorg-" ~ xorg_name %}
{% set am_version = "1.16" %} # keep synchronized with build.sh
{% set am_version_win = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: 5094d1f0fcc1828cb1696d0d39d9e866ae32520c54d01f618f1a3c1e30c2085c

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('xorg-libxinerama', max_pin='x.x') }}
  # Is this one line below still needed?
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - autoconf                         # [not win]
    - automake {{ am_version }}        # [not win]
    - libtool                          # [not win]
    - pkg-config
    - m2-autoconf                      # [win]
    - m2-automake{{ am_version_win }}  # [win]
    - m2-libtool                       # [win]
    - m2-base                          # [win]
    - make                             # [not win]
  host:
    - xorg-util-macros
    - xorg-libx11
    - xorg-xineramaproto
    - xorg-libxext

test:
  commands:
    {% set lib_idents = [ "Xinerama" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}${SHLIB_EXT}
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.dll.a exit /b 1    # [win]
    - if not exist %PREFIX%/Library/bin/msys-{{ lib_ident }}-*.dll exit /b 1  # [win]
    {% endfor %}

about:
  home: https://gitlab.freedesktop.org/xorg/lib/libxinerama
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Client library for the Xinerama extension to the X11 protocol.

extra:
  recipe-maintainers:
    - hmaarrfk
